name: release-tag

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 9 sec
        run: sleep 9s
      - name: Echo a String
        run: echo "Released a new version (Tag)"
