name: release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 5 sec
        run: sleep 5s
      - name: Echo a String
        run: echo "Released a new version (Tag)"
